# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: greeshmahvs370@gmail.com
author_name: Greeshma370
contract_name: ff
deployment_language: python
preset_name: starter
project_name: ff-contracts

